<?php

namespace App;

use App\Scopes\ArchiveScope;
use Illuminate\Database\Eloquent\Model;

class Archive extends File
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ArchiveScope());
    }
}
