<?php

namespace App;

use App\Scopes\FolderScope;

class Folder extends File
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new FolderScope());
    }

    public function getChildren()
    {

        $children = [];

    }

    public static function getChildrenFiles(Folder $folder)
    {
        $childrenFiles = File::where('folder_id', '=', $folder->id)->get();



    }

    public function setIsFolderAttribute()
    {
        $this->attributes['is_folder'] = 1;
    }

    public function files()
    {
        return $this->hasMany(File::class, 'folder_id', 'id');
    }



}
