<?php

namespace App;

use App\Scopes\ArchiveScope;

class Trash extends File
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ArchiveScope());
    }
}
